# 1. Configurações da Aplicação e Segurança
spring.application.name=tocaia-api
api.security.token.secret=TocaiaSecreta123456

# 2. Configurações do Banco de Dados H2 (Em Memória)
spring.datasource.url=jdbc:h2:mem:tocaia_db;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 3. Configuração do Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# 4. Configuração do Flyway
spring.flyway.enabled=true

# 5. Tratamento de Erros HTTP
spring.mvc.problemdetails.enabled=true